#!/bin/sh

### BEGIN INIT INFO
# Provides:          phpminer_rpcclient
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start PHPMiner RPC CLient
# Description:       Start PHPMiner RPC Client service.
### END INIT INFO
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

[ -f /etc/default/rcS ] && . /etc/default/rcS
PATH=/bin:/usr/bin:/sbin:/usr/sbin

# for example this should look like PROGRAM=/var/www/php_cgminer/phpminer_rpcclient/index.php
PROGRAM={/PATH/TO/phpminer_rpcclient}/index.php

# for example this should look like USER=myriguser
USER={USER}

case "$1" in
  start)
        screen -d -m -S phpminer_rpcclient su $USER -c "php -f $PROGRAM"
        ;;
  stop)
        if [ -f /tmp/phpminer_rpcclient.pid ]; then
                cat /tmp/phpminer_rpcclient.pid | awk '{ print "kill "$1; }' | sh
        fi
        ;;
  force-reload|restart)
        $0 stop
        $0 start
        ;;
  status)
        if [ -f /tmp/phpminer_rpcclient.pid ]; then
                echo "PHPMiner RPC Client is running"
        else
                echo "PHPMiner RPC Client is not running"
        fi
        exit 0
        ;;
  *)
        echo "Usage: /etc/init.d/phpminer_rpcclient {start|stop|restart|status}"
        exit 1
esac

exit 0